---
- name: Config from EcoRouter
  hosts: 192.168.2.1
  gather_facts: no
  vars:
    ansible_become_method: enable
  tasks:
    - name: Get running config from EcoRouter
      ansible.netcommon.cli_command:
        command: show running-config
      register: config_output
    - name: Save config to file
      delegate_to: localhost
      copy:
        content: "{{ config_output.stdout }}"
        dest: "/etc/ansible/NETWORK_INFO/{{ inventory_hostname }}.cfg"
- name: 192.168.1.2 playbook 
  hosts: 192.168.1.2 
  gather_facts: no 
  become: yes 
  tasks:
    - name: Start playbook on 192.168.1.2 
      shell: ansible-playbook /etc/ansible/playbook_network.yml 
      
- name: Copy From 192.168.1.2 
  hosts: localhost
  tasks: 
    - name: scp
      shell: sshpass -p "P@ssw0rd" scp -P 2024 sshuser@192.168.1.2:/etc/ansible/NETWORK_INFO/192.168.1.1.cfg /etc/ansible/NETWORK_INFO/192.168.1.1.cfg

